name: biomedscanner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  mobile_scanner: ^5.1.0
  shared_preferences: ^2.2.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Pindahkan flutter_launcher_icons ke sini (digabung):
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
  
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

# Konfigurasi Icon ditaruh paling bawah (Di luar bagian 'flutter'):
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21